version: '3.8'

services:
  mariadb:
    image: mariadb
    build:
      context: ./db/mariadb
      dockerfile: Dockerfile
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    build:
      context: ./db/phpmyadmin
      dockerfile: Dockerfile
    restart: always
    environment:
      - PMA_ARBITRARY=1

  manager:
    image: manager
    build:
      context: ./manager
      dockerfile: Dockerfile
    volumes:
      - manager-data:/root/.local/share/Manager

volumes:
  manager-data:
  mariadb-data:
