version: '3.8'

services:
  nextjs:
    image: nextjs
    build:
      context: ./nextjs
      dockerfile: Dockerfile.dev
    volumes:
      - ./nextjs:/app
    # Keep 3000 port open is necessary to enable hot-reload function for React components
    ports:
     - '3000:3000'

  proxy:
    image: proxy
    build:
      context: ./proxy/dev
      dockerfile: Dockerfile
    ports:
      - '80:80'