FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04

WORKDIR /app

RUN apt update \
        apt install python3 \
        apt install pip

COPY requirements.txt .

RUN pip install --upgrade pip
RUN --mount=type=cache,target=/root/.cache/pip \
        pip install -r requirements.txt

COPY . .

CMD tail -f /dev/null