# Stage 1: Build the React application
FROM node:18-alpine3.18 as build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . /app
RUN npm run build


# Stage 2: Serve the React application from Nginx server
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
# Add custom nginx config
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 

CMD ["nginx", "-g", "daemon off;"]