FROM node:18-alpine3.18

WORKDIR /app

COPY package.json .
RUN npm install
COPY . .

CMD npx prisma migrate deploy\
    && npx prisma generate\
    && npx next dev

# CMD npm install \
#     tail -f /dev/null